services:
  builder:
    build: .
    restart: "no"
    image: modules/getting-at-the-door
    entrypoint: ["sh","-c", "exit 0"]

  app:
    image: local/ttyd-base:latest
    read_only: true
    runtime: runc
    depends_on:
      - builder
    container_name: dockerpr02.<REPLACE_DOMAIN>
    restart: unless-stopped
    command: sh /run.sh
    volumes:
      - ${PWD}/docker-compose.module.yml:/docker-compose.yml
      - ${PWD}/run.sh:/run.sh
    security_opt:
      - no-new-privileges:true
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dockerpr02.rule=Host(`dockerpr02.<REPLACE_DOMAIN>`)'
      - 'traefik.http.routers.dockerpr02.entrypoints=websecure'
      - 'traefik.http.routers.dockerpr02.middlewares=authelia@docker'
    expose:
      - 4242
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      proxy:

networks:
  proxy:
    external:
      name: docker-net-proxy