services:
  builder:
    build: .
    restart: "no"
    image: modules/flag-in-container
    entrypoint: ['exit', '0']
    #entrypoint: "bash -c"
    #command: "exit 0"

  app:
    image: ttyd-base
    runtime: runc
    depends_on:
      - builder
    container_name: fic.<REPLACE_DOMAIN>
    restart: unless-stopped
    command: docker run -it --rm modules/flag-in-container
    security_opt:
      - no-new-privileges:true
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.fic.rule=Host(`fic.<REPLACE_DOMAIN>`)'
      - 'traefik.http.routers.fic.entrypoints=websecure'
      - 'traefik.http.routers.traefik.middlewares=authelia@docker'
    expose:
      - 4242
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      proxy:

networks:
  proxy:
    external:
      name: docker-net-proxy