###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: debug
log_file_path: /config/authelia.log

# TODO (glost) Check, if this is needed
default_redirection_url: https://public.<REPLACE_DOMAIN>

totp:
  issuer: <REPLACE_DOMAIN>

authentication_backend:
  # TODO (glost) Without proper eMail config, this will not work anyways
  disable_reset_password: true
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024

access_control:
  default_policy: one_factor
  rules:
    # Rules applied to everyone
    - domain: public.<REPLACE_DOMAIN>
      policy: bypass

session:
  name: authelia_session
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: <REPLACE_DOMAIN> # Should match whatever your root protected domain is

  redis:
    host: redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  postgres:
    host: db
    port: 5432
    database: authelia
    username: authelia
    sslmode: disable