###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# TODO (glost) 1) Choice of LDAP or this 2) Dynamic default user
# List of users
users:
  saraswati:
    displayname: "Saraswati Admin"
    password: "<REPLACE_ADMIN_PW>"
    email: <REPLACE_EMAIL>
    groups:
      - admins
      - dev
